/**
 * OneClickStyle
 * Trabajo Final de Platzi Master C2
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.api

import io.swagger.client.model.User
import io.swagger.client.core._
import io.swagger.client.core.CollectionFormats._
import io.swagger.client.core.ApiKeyLocations._

object UserApi {

  /**
   * Crea un usuario en nuestra app
   * 
   * Expected answers:
   *   code 0 :  (successful operation)
   * 
   * @param body Usuario creado
   */
  def createUser(body: User): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.POST, "http://localhost:3000/api", "/user", "application/json")
      .withBody(body)
      .withDefaultSuccessResponse[Unit]
        /**
   * 
   * 
   * Expected answers:
   *   code 0 :  (Lista de usuarios)
   */
  def listUser(): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.GET, "http://localhost:3000/api", "/user", "application/json")
      .withDefaultSuccessResponse[Unit]
      

}

